#默认访问路径是http://localhost:8080，我将之改为http://localhost:8081/helloboot
#server.context-path=/helloboot

#Tomcat默认端口是8080，我将之改为8081
#server.port=8081

usename: 红楼梦
pwd: 123456

#设置spring-boot 编码格式
banner.charset: UTF-8
server.tomcat.uri-encoding: UTF-8
spring.http.encoding:
                 charset: UTF-8
                 enabled: true
                 force: true
spring.messages.encoding: UTF-8


#log相关
#logging.file: F://log.log
logging.path: D://log
logging.level.org.springframework.web: debug
#控制台打印sql语句
logging.level.com.levin: DEBUG




#---------jdbc相关 start--------
server:
  port: 8080

spring:
    datasource:
        name: beta
        url: jdbc:mysql://10.32.64.20:3306/schair
        username: beta
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.levin.demo

#---------jdbc相关 end--------

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql



#ResponseData是我们返回格式的实体类
#这种在发生错误时这边会捕获到，然后封装好返回格式，返回给调用方
#最后关键的一步是在spring boot的配置文件中加上如下配置：
#出现错误时, 直接抛出异常
spring.mvc.throw-exception-if-no-handler-found: true
spring.resources.add-mappings: false



#定时任务，默认每秒执行一次,之后可通过接口修改
cron:
 pattern:
        test: 0/1 * * * * ?

 #rabbitmq 相关配置
 spring.application.name: springBoot3
 spring.rabbitmq:
            host: 127.0.0.1
            port: 5672
            username: guest
            password: guest
            publisher-confirms: true
            virtual-host: /


spring.thymeleaf:
          prefix: classpath:/pages/
          suffix: .html
          cache: false
          mode: HTML5
          encoding: UTF-8
          content-type: text/html

#指定配置文件
#mybatis.config-location=classpath:mybatis-config.xml


